services:
  postgres:
    container_name: postgres-sc
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Borman15
      POSTGRES_DB: soundscape
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  postgres:
    driver: local
